import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin-SkillKing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transparent-scrollbar`}
      >
         <Toaster
        position="top-center"
        reverseOrder={false}
        toastOptions={{
          success: {
            style: {
              background: 'linear-gradient(to right, #6a0dad, #ff007f)',  // Purple-Pink Gradient
              color: 'white',
              padding: '12px 20px',
              borderRadius: '8px',
              fontWeight: 'bold',
              fontSize: '16px',
              boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.2)',
            },
          },
          error: {
            style: {
              background: 'linear-gradient(to right, #ff0033, #e40000)', // Red gradient for error
              color: 'white',
              padding: '12px 20px',
              borderRadius: '8px',
              fontWeight: 'bold',
              fontSize: '16px',
              boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.2)',
            },
          },
          loading: {
            style: {
              background: 'linear-gradient(to right, #ff7f00, #ffba00)',  // Yellow-Orange gradient for loading
              color: 'white',
              padding: '12px 20px',
              borderRadius: '8px',
              fontWeight: 'bold',
              fontSize: '16px',
              boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.2)',
            },
          },
        }}
      />
        {children}
      </body>
    </html>
  );
}
